
export default new Map([
["src/content/projects/ad-html-page.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fad-html-page.mdx&astroContentModuleFlag=true")],
["src/content/projects/asset-inventory-webpage.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fasset-inventory-webpage.mdx&astroContentModuleFlag=true")],
["src/content/projects/quick-send-project.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fquick-send-project.mdx&astroContentModuleFlag=true")],
["src/content/projects/courselink-grader.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fcourselink-grader.mdx&astroContentModuleFlag=true")],
["src/content/projects/react-movie-watchlist.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Freact-movie-watchlist.mdx&astroContentModuleFlag=true")],
["src/content/projects/manage-engine-api.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fmanage-engine-api.mdx&astroContentModuleFlag=true")],
["src/content/projects/raycast-overseerr-requesterr.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fraycast-overseerr-requesterr.mdx&astroContentModuleFlag=true")],
["src/content/projects/stencil-ai.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fstencil-ai.mdx&astroContentModuleFlag=true")],
["src/content/research/generative-ai-medical-imaging.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fresearch%2Fgenerative-ai-medical-imaging.mdx&astroContentModuleFlag=true")],
["src/content/research/cxr-segmentation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fresearch%2Fcxr-segmentation.mdx&astroContentModuleFlag=true")],
["src/content/projects/tile-slide-puzzle.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Ftile-slide-puzzle.mdx&astroContentModuleFlag=true")],
["src/content/research/ml-bug-detection-system.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fresearch%2Fml-bug-detection-system.mdx&astroContentModuleFlag=true")],
["src/content/research/portfolio-communication-as-interface-design.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fresearch%2Fportfolio-communication-as-interface-design.mdx&astroContentModuleFlag=true")]]);
		