
import __ASTRO_IMAGE_IMPORT_Z2cUhXB from "../../assets/images/cxr-segmentation-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fcxr-segmentation.mdx";
import __ASTRO_IMAGE_IMPORT_1rLOmh from "../../assets/images/cxr-segmentation-page.png?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fcxr-segmentation.mdx";
import __ASTRO_IMAGE_IMPORT_24CUaT from "../../assets/images/presenting.png?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fgenerative-ai-medical-imaging.mdx";
import __ASTRO_IMAGE_IMPORT_ZCwUWB from "../../assets/images/presenting_full.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fgenerative-ai-medical-imaging.mdx";
import __ASTRO_IMAGE_IMPORT_Z1fCu8V from "../../assets/images/nevvon-flow.png?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fml-bug-detection-system.mdx";
import __ASTRO_IMAGE_IMPORT_Z4ml2O from "../../assets/images/asset-management-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fasset-inventory-webpage.mdx";
import __ASTRO_IMAGE_IMPORT_Nn7Ri from "../../assets/images/asset-management-page.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fasset-inventory-webpage.mdx";
import __ASTRO_IMAGE_IMPORT_Z1sm9Ow from "../../assets/images/ad-html-page-card.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fad-html-page.mdx";
import __ASTRO_IMAGE_IMPORT_1cYTlo from "../../assets/images/ad-html-page-page.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fad-html-page.mdx";
import __ASTRO_IMAGE_IMPORT_2uzVoi from "../../assets/images/send_recv_help_command.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fquick-send-project.mdx";
import __ASTRO_IMAGE_IMPORT_Z1rVKOP from "../../assets/images/react-watchlist.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Freact-movie-watchlist.mdx";
import __ASTRO_IMAGE_IMPORT_wGkpX from "../../assets/images/stencil-ai-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fstencil-ai.mdx";
import __ASTRO_IMAGE_IMPORT_Za44st from "../../assets/images/stencil-ai-page.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fstencil-ai.mdx";
import __ASTRO_IMAGE_IMPORT_1EpbUE from "../../assets/images/overseerr-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fraycast-overseerr-requesterr.mdx";
import __ASTRO_IMAGE_IMPORT_1EcGk5 from "../../assets/images/overseerr-page.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fraycast-overseerr-requesterr.mdx";
export default new Map([["../../assets/images/cxr-segmentation-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fcxr-segmentation.mdx", __ASTRO_IMAGE_IMPORT_Z2cUhXB], ["../../assets/images/cxr-segmentation-page.png?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fcxr-segmentation.mdx", __ASTRO_IMAGE_IMPORT_1rLOmh], ["../../assets/images/presenting.png?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fgenerative-ai-medical-imaging.mdx", __ASTRO_IMAGE_IMPORT_24CUaT], ["../../assets/images/presenting_full.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fgenerative-ai-medical-imaging.mdx", __ASTRO_IMAGE_IMPORT_ZCwUWB], ["../../assets/images/nevvon-flow.png?astroContentImageFlag=&importer=src%2Fcontent%2Fresearch%2Fml-bug-detection-system.mdx", __ASTRO_IMAGE_IMPORT_Z1fCu8V], ["../../assets/images/asset-management-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fasset-inventory-webpage.mdx", __ASTRO_IMAGE_IMPORT_Z4ml2O], ["../../assets/images/asset-management-page.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fasset-inventory-webpage.mdx", __ASTRO_IMAGE_IMPORT_Nn7Ri], ["../../assets/images/ad-html-page-card.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fad-html-page.mdx", __ASTRO_IMAGE_IMPORT_Z1sm9Ow], ["../../assets/images/ad-html-page-page.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fad-html-page.mdx", __ASTRO_IMAGE_IMPORT_1cYTlo], ["../../assets/images/send_recv_help_command.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fquick-send-project.mdx", __ASTRO_IMAGE_IMPORT_2uzVoi], ["../../assets/images/react-watchlist.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Freact-movie-watchlist.mdx", __ASTRO_IMAGE_IMPORT_Z1rVKOP], ["../../assets/images/stencil-ai-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fstencil-ai.mdx", __ASTRO_IMAGE_IMPORT_wGkpX], ["../../assets/images/stencil-ai-page.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fstencil-ai.mdx", __ASTRO_IMAGE_IMPORT_Za44st], ["../../assets/images/overseerr-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fraycast-overseerr-requesterr.mdx", __ASTRO_IMAGE_IMPORT_1EpbUE], ["../../assets/images/overseerr-page.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fraycast-overseerr-requesterr.mdx", __ASTRO_IMAGE_IMPORT_1EcGk5]]);
		